### ISSUE TITLE
Product Items price doesn't convert currency

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#136]
We need to define logic here

**Comment by perminder-klair** [comment]
Few questions @dimarconicola @Alexintosh 

- Does each store has it's own products? If yes, this feature is only available to logged in users
- When we add Products in database, do we add them in base currency set for store?
- What happens if store changes it's currency in future? 

Simple questions, but just want to confirm them first

**Comment by Alexintosh** [comment]
1. Definitely.
2. Looks reasonable to me
3. Good point, for now I'd just give a reminder to update the products price if any.

Thoughts?

**Comment by dimarconicola** [comment]
I thought that was possible to:
- store the product to the database with the currency selected at that moment (i.e. Beer=3.50USD)
- convert that value to the newly selected currency in case of the merchant change base currency
